<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1417600155660/sayHelloImpl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="Untitled" targetNamespace="http://xmlns.example.com/1417600155660/sayHelloImpl">
    <wsdl:types/>
    <wsdl:service name="myServiceImpl">
        <wsdl:port binding="tns:SOAPEventSourceBinding" name="SOAPEventSource">
            <soap:address location="http://localhost:5001/myServiceImpl"/>
        </wsdl:port>
    </wsdl:service>
    <wsdl:portType name="MessagePort">
        <wsdl:operation name="sayHello">
            <wsdl:input message="tns:HelloRequest"/>
            <wsdl:output message="tns:HelloReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SOAPEventSourceBinding" type="tns:MessagePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sayHello">
            <soap:operation soapAction="/myServiceImpl" style="document"/>
            <wsdl:input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://InputMessageNamespace" parts="name" use="encoded"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://OutputMessageNamespace" parts="response" use="encoded"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="HelloRequest">
        <wsdl:part name="name" type="xs:string"/>
    </wsdl:message>
    <wsdl:message name="HelloReply">
        <wsdl:part name="response" type="xs:string"/>
    </wsdl:message>
</wsdl:definitions>